### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by allpan3** [ebullient/obsidian-slides-extended#28] opened 2024-09-15 01:35 UTC
### Input data (markdown source)

Leading text like `<` or `s`

### Expected Behavior

Show the autocomplete menu

### Current behaviour

Not showing

### Steps to reproduce

Tested in sandbox and it's not working. Tried the same with the original advanced slides plugin. It works fine.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version

1.6.7

### Slides Extended Plugin Version

2.1.2

### Checks

- [x] I have tried it in the sandbox vault with only this plugin enabled

**Comment by ebullient** [comment] 2024-10-07 13:32
This is expected. I disabled autocomplete due to #20, and I haven't had a chance to figure out why it misbehaves.

**Comment by ebullient** [comment] 2024-10-07 13:33
closing as duplicate of #20

**Closed by ebullient** 2024-10-07 13:33 UTC
